name: hello-world
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Clone-down
        uses: actions/checkout@v3
      - name: Build 
        run: chmod +x ci/build-app.sh && ci/build-app.sh
      - name: Test
        run: ci/unit-test-app.sh
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: code
          path: .
  docker-image:
    runs-on: ubuntu-latest
    needs: [build]
    permissions:
      packages: write
    steps:
      - name: download artifact
        uses: actions/download-artifact@v3
        with:
          name: code
          path: .
      - name: Login to docker-image
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and deploy
        uses: docker/build-push-action@v3
        with:
          content: app
          push: tree 
          tags: ghcr.io/${{ github.actor }}/micronaut-app:1.0-${{ github.sha }},ghcr.io/${{ github.actor }}/micronaut-app:latest


